apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: cilium-state-writer
  name: cilium-state-writer
spec:
  selector:
    matchLabels:
      k8s-app: cilium-state-writer
  template:
    metadata:
      labels:
        k8s-app: cilium-state-writer
    spec:
      containers:
      - command:
        - state-writer
        env:
        - name: CILIUM_VERSION
          value: "1.6.7 0000000 2020-05-13T22:55:12-08:00 go version go1.12.5 linux/amd64"
        image: "quay.io/cilium/state-writer:0.1"
        imagePullPolicy: IfNotPresent
        name: state-writer
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
        volumeMounts:
        - mountPath: /var/run/cilium
          name: cilium-run
      hostNetwork: true
      restartPolicy: Always
      serviceAccount: cilium
      serviceAccountName: cilium
      volumes:
      - hostPath:
          path: /var/run/cilium
          type: DirectoryOrCreate
        name: cilium-run
